### ISSUE TITLE
How can we overwrite arrays with environment variables?

### ISSUE THREAD

**Issue by Rfrixy** [smartprix/cfg#10]
From the docs I can see that we can overwrite a certain element in an array. Is there any way to change the whole array, such as making it shorter?

e.g.
['a', 'b', 'c'] -> default

['a', 'd'] -> from env vars

**Comment by rohit-gohri** [comment]
Difficult with env vars, max you can do is set the extra index to empty string and filter it out using a getter.

```
const cfg = require('@smpx/cfg');

module.exports = {
  rawVal = ['a', 'b', 'c'],
  get val() {
    return cfg('rawVal').filter(Boolean);
  },
};
```

and then `CFG__RAW_VAL__2=''` I think would allow to make it shorter.

**Comment by hit12369** [comment]
This is now supported in `1.4.0`.

Now you can pass any arbitrary JSON in environment variables by prefixing with `@JSON:`  
`CFG__A='@JSON:["a", "b", "c"]' CFG__B='@JSON:3'`
