### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by Rfrixy** [smartprix/cfg#8]
Some sort of path issue, crashes with 'Only absolute paths are allowed' on startup.

**Comment by rohit-gohri** [comment]
Probably have to use path.join in all of these places instead of adding manual slashes in path:
https://github.com/smartprix/cfg/blob/d8251c413d6c3861193d9551e33a9d2e3ee63b00/index.js#L77-L82

As windows has different slash in it's path.

**Comment by hit12369** [comment]
Also, have to change this to `path.isAbsolute`
https://github.com/smartprix/cfg/blob/master/index.js#L187-L189

**Comment by hit12369** [comment]
Fixed in https://github.com/smartprix/cfg/commit/2dbe896cbe85e793d6bbbaf6fb04863359bdd1f1

Though I don't have a windows machine to test right now, @Rfrixy can you confirm if it's working?

**Comment by hit12369** [comment]
Released in `1.3.0`

**Comment by Rfrixy** [comment]
@hit12369  Yes it works, thank you!
